"""
Markdown reports generated from computed results.

Every statement of pass/fail in these reports is derived from data; nothing is typed in.
"""

from __future__ import annotations

from typing import Any, Dict, List


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def data_quality_report(run_id: str, qc: Dict[str, Any], crosscheck: Dict[str, Dict[str, Any]],
                        manifest: Dict[str, Any], cfg_raw: Dict[str, Any]) -> str:
    gates = qc["gates"]
    lines = [
        "# Data Quality Report",
        "",
        f"Run `{run_id}` · period {cfg_raw['start_date']} → {cfg_raw['end_date']} · generated by `python -m src.pipeline run`",
        "",
        "## Quality gates",
        "",
        "| Gate | Measured | Limit | Result |",
        "|---|---:|---:|---|",
        f"| ERA5 target missing (daylight hours) | {_pct(gates['target_null_fraction_daylight'])} | {_pct(gates['target_null_limit'])} | "
        f"{'PASS' if gates['target_null_fraction_daylight'] <= gates['target_null_limit'] else 'FAIL'} |",
        f"| Primary NWP GHI missing (test daylight hours) | {_pct(gates['primary_ghi_null_fraction_test_daylight'])} | "
        f"{_pct(gates['primary_ghi_null_limit'])} | "
        f"{'PASS' if gates['primary_ghi_null_fraction_test_daylight'] <= gates['primary_ghi_null_limit'] else 'FAIL'} |",
        "",
        "Missing values are kept as missing. The model handles them natively; nothing is filled with zeros.",
        "",
        "## Raw files",
        "",
        "| File | Source | Model | Rows | Variables dropped (no data from API) |",
        "|---|---|---|---:|---|",
    ]
    for e in manifest.get("files", []):
        lines.append(f"| `{e['file']}` | {e['source']} | {e['model']} | {e['rows']:,} | {', '.join(e['dropped_all_null_variables']) or '—'} |")

    lines += ["", "## Timestamp integrity", "", "| Site | Source | Missing timestamps | Duplicates | Off-grid | Negative values clipped |",
              "|---|---|---:|---:|---:|---:|"]
    for site in qc["sites"]:
        for source, st in site["sources"].items():
            lines.append(f"| {site['site_id']} | {source} | {st['missing_timestamps']} | {st['duplicate_timestamps']} | "
                         f"{st['off_grid_timestamps']} | {st['negative_values_clipped']} |")

    lines += ["", "## Missing data by year (daylight hours)", "",
              "Share of daylight hours with no value, per site, year and key variable.", ""]
    key_vars = ["ghi_actual"] + [f"{p}_shortwave_radiation" for p in cfg_raw["nwp"]["models"]] + \
               [f"{p}_cloud_cover" for p in cfg_raw["nwp"]["models"]]
    lines.append("| Site | Year | " + " | ".join(f"`{v}`" for v in key_vars) + " |")
    lines.append("|---|---|" + "---:|" * len(key_vars))
    for site in qc["sites"]:
        for year, fr in site["null_fraction_daylight"].items():
            cells = [(_pct(fr[v]) if v in fr else "n/a") for v in key_vars]
            lines.append(f"| {site['site_id']} | {year} | " + " | ".join(cells) + " |")

    lines += ["", "## ERA5 vs NASA POWER cross-check", "",
              "NASA POWER is requested in UTC. The hour offset that best aligns it with ERA5 is searched rather than assumed;",
              "agreement requires hourly correlation ≥ 0.9, an offset of at most 1 h and a mean daily difference ≤ 15%.", "",
              "| Site | Best offset (h) | Hourly r | r at 0 h | Hourly MAE (W/m²) | Hourly bias (W/m²) | Daily diff | Days | Status |",
              "|---|---:|---:|---:|---:|---:|---:|---:|---|"]
    for sid, r in crosscheck.items():
        lines.append(f"| {sid} | {r['best_lag_hours']:+.1f} | {r['hourly_correlation']:.3f} | {r['correlation_at_zero_lag']:.3f} | "
                     f"{r['hourly_mae_wm2']:.1f} | {r['hourly_bias_wm2']:+.1f} | {r['daily_mean_abs_diff_pct']:.1f}% | "
                     f"{r['days_compared']} | {r['status']} |")
    lines += ["", f"Offset convention: {next(iter(crosscheck.values()))['lag_meaning'] if crosscheck else ''}.", "",
              "## Known limitations", "",
              f"- {cfg_raw['truth']['note']}",
              f"- Issue time: {cfg_raw['issue_time']['description']}",
              ""]
    return "\n".join(lines)


def evaluation_report(metrics: Dict[str, Any], selection: Dict[str, Any], forecaster: Dict[str, Any],
                      feature_groups: Dict[str, List[str]]) -> str:
    o, a, dly = metrics["overall"], metrics["all_hours"], metrics["daily"]
    ci = o["skill_interval"]["vs_raw_nwp"]
    beats_nwp = ci["low"] > 0
    lines = [
        "# Evaluation Report",
        "",
        f"Model `{metrics['model_version']}` · run `{metrics['run_id']}` · test period {metrics['test_period']['start']} → {metrics['test_period']['end']}",
        "",
        metrics["convention"],
        "",
        "## Headline (daylight hours, W/m²)",
        "",
        "| Model | MAE | RMSE | nRMSE % | Bias | Skill % |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for key, label in (("ml_model_p50", "ML P50 (skill vs raw NWP)"), ("raw_nwp", "Raw NWP (skill vs persistence)"),
                       ("persistence", "Persistence (idealised)")):
        m = o[key]
        lines.append(f"| {label} | {m['mae']:.2f} | {m['rmse']:.2f} | {m['nrmse']:.2f} | {m['bias']:+.2f} | {m['skill']:+.2f} |")
    lines += [
        "",
        f"- Skill vs raw NWP: {o['ml_model_p50']['skill']:+.2f}% with a {int(ci['level'] * 100)}% day-block bootstrap interval of "
        f"[{ci['low']:+.2f}%, {ci['high']:+.2f}%]. "
        + ("The interval excludes zero, so the improvement over raw NWP, measured against ERA5, is supported." if beats_nwp
           else "The interval includes zero, so the test period does not establish an improvement over raw NWP, even against ERA5."),
        f"- P10–P90 coverage: {o['p10_p90_coverage']:.2f}% of daylight hours (target 75–85%); quantile crossings: {o['quantile_crossings']}.",
        f"- Pinball loss: " + ", ".join(f"{k} {v:.2f}" for k, v in o["pinball"].items()) + " W/m².",
        f"- All hours (for comparison only): ML MAE {a['ml_model_p50']['mae']:.2f}, raw NWP {a['raw_nwp']['mae']:.2f}, "
        f"persistence {a['persistence']['mae']:.2f} W/m²; coverage {a['p10_p90_coverage']:.2f}%.",
        f"- Daily irradiation: ML MAE {dly['ml_model_p50']['mae']:.3f} kWh/m² (skill vs NWP {dly['ml_model_p50']['skill']:+.2f}%), "
        f"daily P10–P90 coverage {dly['p10_p90_coverage']:.2f}% over {dly['days']} site-days.",
    ]
    ind = metrics.get("independent_check")
    if ind:
        ml, nwp, era5 = ind["ml_model_p50"], ind["raw_nwp"], ind["era5"]
        verdict = ("The ML forecast also beats raw NWP against this reference." if ml["mae"] < nwp["mae"] else
                   "Against this reference the ML forecast does NOT beat raw NWP: its gain against ERA5 mostly reflects "
                   "learning ERA5's systematic differences from the NWP input, not better prediction of measured sunlight.")
        lines += [
            "",
            f"## Independent check against {ind['reference']}",
            "",
            "Neither the model nor its NWP input was fitted to this reference, so it shows whether the gain against ERA5 carries over.",
            "",
            "| Forecast | MAE vs reference | Bias | Skill vs raw NWP % |",
            "|---|---:|---:|---:|",
            f"| ML P50 | {ml['mae']:.2f} | {ml['bias']:+.2f} | {ml['skill']:+.2f} |",
            f"| Raw NWP | {nwp['mae']:.2f} | {nwp['bias']:+.2f} | |",
            f"| ERA5 itself | {era5['mae']:.2f} | {era5['bias']:+.2f} | |",
            "",
            f"{verdict} ({ind['rows']:,} daylight test hours.)",
        ]
    lines += [
        "",
        "## By site (daylight hours)",
        "",
        "| Site | ML MAE | Raw NWP MAE | Skill % | Skill interval | Coverage % |",
        "|---|---:|---:|---:|---|---:|",
    ]
    for sid, s in metrics["by_site"].items():
        si = s["skill_interval"]["vs_raw_nwp"]
        lines.append(f"| {s['name']} | {s['ml_model_p50']['mae']:.2f} | {s['raw_nwp']['mae']:.2f} | {s['ml_model_p50']['skill']:+.2f} | "
                     f"[{si['low']:+.2f}, {si['high']:+.2f}] | {s['coverage']:.2f} |")
    lines += ["", "## By confidence level (daylight hours)", "", "| Level | Site-days | MAE | Coverage % |", "|---|---:|---:|---:|"]
    for lvl, c in metrics["by_confidence"].items():
        lines.append(f"| {lvl} | {c['site_days']} | {c['mae']:.2f} | {c['coverage']:.2f} |")
    lines += [
        "",
        "## Choices made on the validation year",
        "",
        f"- Blend weight with raw NWP (per site): {forecaster['blend_weight']}",
        f"- Band multiplier (per site): {forecaster['band_multiplier']}",
        f"- Daily band multiplier: {forecaster['daily_band_multiplier']}",
        f"- Confidence thresholds: {[round(t, 4) for t in forecaster['confidence_thresholds']]}",
        f"- Trees after refit: {forecaster['trees']}",
        f"- Validation MAE by site: {selection.get('validation_mae')}; raw NWP: {selection.get('validation_mae_raw_nwp')}",
        f"- Validation coverage by site: {selection.get('validation_coverage')}; daily: {selection.get('validation_daily_coverage')}",
        "",
        "## Features",
        "",
        "Every feature is available when the forecast is issued; the pipeline refuses to build one derived from observations.",
        "",
    ]
    for source, names in feature_groups.items():
        lines.append(f"- **{source}** ({len(names)}): " + ", ".join(f"`{n}`" for n in names))
    lines.append("")
    return "\n".join(lines)
